---
detectors:
  IrresponsibleModule:
    enabled: false
exclude_paths:
  - _snippets
  - lib/job_info.rb # one-time test fixture 

detectors:
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 10
