---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"
  SESSION_SECRET: "SESSION_SECRET"
  APP_HOST: http://localhost:9000

app_test:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"
  SESSION_SECRET: "SESSION_SECRET"
  # Application
  APP_HOST: http://localhost:9000

production:
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"
  SESSION_SECRET: "SESSION_SECRET"
  APP_HOST: http://url.to.app
