---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  RESUME_TOKEN: "THIS_IS_A_DUMMY_KEY"
